// https://github.com/LiteLDev/LegacyScriptEngine/blob/main/src/legacy/api/EntityAPI.cpp

external class LLSE_Entity(nullptr: Nothing) {
    //.instanceFunction("asPointer", &EntityClass::asPointer)

    //.instanceProperty("name", &EntityClass::getName)
    //.instanceProperty("type", &EntityClass::getType)
    //.instanceProperty("id", &EntityClass::getId)
    //.instanceProperty("pos", &EntityClass::getPos)
    //.instanceProperty("posDelta", &EntityClass::getPosDelta)
    //.instanceProperty("feetPos", &EntityClass::getFeetPos)
    //.instanceProperty("blockPos", &EntityClass::getBlockPos)
    //.instanceProperty("maxHealth", &EntityClass::getMaxHealth)
    //.instanceProperty("health", &EntityClass::getHealth)
    //.instanceProperty("canFly", &EntityClass::getCanFly)
    //.instanceProperty("canFreeze", &EntityClass::getCanFreeze)
    //.instanceProperty("canSeeDaylight", &EntityClass::getCanSeeDaylight)
    //.instanceProperty("canPickupItems", &EntityClass::getCanPickupItems)
    //.instanceProperty("inAir", &EntityClass::getInAir)
    //.instanceProperty("inWater", &EntityClass::getInWater)
    //.instanceProperty("inLava", &EntityClass::getInLava)
    //.instanceProperty("inRain", &EntityClass::getInRain)
    //.instanceProperty("inSnow", &EntityClass::getInSnow)
    //.instanceProperty("inWall", &EntityClass::getInWall)
    //.instanceProperty("inWaterOrRain", &EntityClass::getInWaterOrRain)
    //.instanceProperty("inWorld", &EntityClass::getInWorld)
    //.instanceProperty("speed", &EntityClass::getSpeed)
    //.instanceProperty("direction", &EntityClass::getDirection)
    //.instanceProperty("uniqueId", &EntityClass::getUniqueID)
    //.instanceProperty("isInvisible", &EntityClass::isInvisible)
    //.instanceProperty("isInsidePortal", &EntityClass::isInsidePortal)
    //.instanceProperty("isTrusting", &EntityClass::isTrusting)
    //.instanceProperty("isTouchingDamageBlock", &EntityClass::isTouchingDamageBlock)
    //.instanceProperty("isOnFire", &EntityClass::isOnFire)
    //.instanceProperty("isOnGround", &EntityClass::isOnGround)
    //.instanceProperty("isOnHotBlock", &EntityClass::isOnHotBlock)
    //.instanceProperty("isTrading", &EntityClass::isTrading)
    //.instanceProperty("isRiding", &EntityClass::isRiding)
    //.instanceProperty("isDancing", &EntityClass::isDancing)
    //.instanceProperty("isSleeping", &EntityClass::isSleeping)
    //.instanceProperty("isAngry", &EntityClass::isAngry)
    //.instanceProperty("isBaby", &EntityClass::isBaby)
    //.instanceProperty("isMoving", &EntityClass::isMoving)

    //.instanceFunction("teleport", &EntityClass::teleport)
    //.instanceFunction("kill", &EntityClass::kill)
    //.instanceFunction("despawn", &EntityClass::despawn)
    //.instanceFunction("remove", &EntityClass::remove)
    //.instanceFunction("hurt", &EntityClass::hurt)
    //.instanceFunction("heal", &EntityClass::heal)
    //.instanceFunction("setPosDelta", &EntityClass::setPosDelta)
    //.instanceFunction("setHealth", &EntityClass::setHealth)
    //.instanceFunction("setAbsorption", &EntityClass::setAbsorption)
    //.instanceFunction("setAttackDamage", &EntityClass::setAttackDamage)
    //.instanceFunction("setMaxAttackDamage", &EntityClass::setMaxAttackDamage)
    //.instanceFunction("setFollowRange", &EntityClass::setFollowRange)
    //.instanceFunction("setKnockbackResistance", &EntityClass::setKnockbackResistance)
    //.instanceFunction("setLuck", &EntityClass::setLuck)
    //.instanceFunction("setMovementSpeed", &EntityClass::setMovementSpeed)
    //.instanceFunction("setUnderwaterMovementSpeed", &EntityClass::setUnderwaterMovementSpeed)
    //.instanceFunction("setLavaMovementSpeed", &EntityClass::setLavaMovementSpeed)
    //.instanceFunction("setMaxHealth", &EntityClass::setMaxHealth)
    //.instanceFunction("setFire", &EntityClass::setFire)
    //.instanceFunction("stopFire", &EntityClass::stopFire)
    //.instanceFunction("isPlayer", &EntityClass::isPlayer)
    //.instanceFunction("toPlayer", &EntityClass::toPlayer)
    //.instanceFunction("isItemEntity", &EntityClass::isItemEntity)
    //.instanceFunction("toItem", &EntityClass::toItem)
    //.instanceFunction("getBlockStandingOn", &EntityClass::getBlockStandingOn)
    //.instanceFunction("getArmor", &EntityClass::getArmor)
    //.instanceFunction("distanceTo", &EntityClass::distanceTo)
    //.instanceFunction("distanceToSqr", &EntityClass::distanceToSqr)
    //.instanceFunction("hasContainer", &EntityClass::hasContainer)
    //.instanceFunction("getContainer", &EntityClass::getContainer)
    //.instanceFunction("refreshItems", &EntityClass::refreshItems)
    //.instanceFunction("setScale", &EntityClass::setScale)
    //.instanceFunction("setNbt", &EntityClass::setNbt)
    //.instanceFunction("getNbt", &EntityClass::getNbt)
    //.instanceFunction("addTag", &EntityClass::addTag)
    //.instanceFunction("removeTag", &EntityClass::removeTag)
    //.instanceFunction("hasTag", &EntityClass::hasTag)
    //.instanceFunction("getAllTags", &EntityClass::getAllTags)
    //.instanceFunction("getEntityFromViewVector", &EntityClass::getEntityFromViewVector)
    //.instanceFunction("getBlockFromViewVector", &EntityClass::getBlockFromViewVector)
    //.instanceFunction("getBiomeName", &EntityClass::getBiomeName)
    //.instanceFunction("getBiomeId", &EntityClass::getBiomeId)
    //.instanceFunction("quickEvalMolangScript", &EntityClass::quickEvalMolangScript)

    //.instanceFunction("getAllEffects", &EntityClass::getAllEffects)
    //.instanceFunction("addEffect", &EntityClass::addEffect)
    //.instanceFunction("removeEffect", &EntityClass::removeEffect)

    // For Compatibility
    //.instanceFunction("setTag", &EntityClass::setNbt)
    //.instanceFunction("setOnFire", &EntityClass::setOnFire)
    //.instanceFunction("getTag", &EntityClass::getNbt)
    //.instanceFunction("distanceToPos", &EntityClass::distanceTo)
}
typealias Entity = LLSE_Entity

external class ActorDamageCause {
    companion object {
        //.property("Override", []() { return Number::newNumber(0); })
        //.property("Contact", []() { return Number::newNumber(1); })
        //.property("EntityAttack", []() { return Number::newNumber(2); })
        //.property("Projectile", []() { return Number::newNumber(3); })
        //.property("Suffocation", []() { return Number::newNumber(4); })
        //.property("Fall", []() { return Number::newNumber(5); })
        //.property("Fire", []() { return Number::newNumber(6); })
        //.property("FireTick", []() { return Number::newNumber(7); })
        //.property("Lava", []() { return Number::newNumber(8); })
        //.property("Drowning", []() { return Number::newNumber(9); })
        //.property("BlockExplosion", []() { return Number::newNumber(10); })
        //.property("EntityExplosion", []() { return Number::newNumber(11); })
        //.property("Void", []() { return Number::newNumber(12); })
        //.property("Suicide", []() { return Number::newNumber(13); })
        //.property("Magic", []() { return Number::newNumber(14); })
        //.property("Wither", []() { return Number::newNumber(15); })
        //.property("Starve", []() { return Number::newNumber(16); })
        //.property("Anvil", []() { return Number::newNumber(17); })
        //.property("Thorns", []() { return Number::newNumber(18); })
        //.property("FallingBlock", []() { return Number::newNumber(19); })
        //.property("Piston", []() { return Number::newNumber(20); })
        //.property("FlyIntoWall", []() { return Number::newNumber(21); })
        //.property("Magma", []() { return Number::newNumber(22); })
        //.property("Fireworks", []() { return Number::newNumber(23); })
        //.property("Lightning", []() { return Number::newNumber(24); })
        //.property("Charging", []() { return Number::newNumber(25); })
        //.property("Temperature", []() { return Number::newNumber(26); })
        //.property("Freezing", []() { return Number::newNumber(27); })
        //.property("Stalactite", []() { return Number::newNumber(28); })
        //.property("Stalagmite", []() { return Number::newNumber(29); })
    }
}
